version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: beebilling_sqlserver
    environment:
      SA_PASSWORD: "Omnibees!Loc@l2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1440:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - beebilling-network

  api:
    build:
      context: .
      dockerfile: Omnibees.BeeBilling.Api/Dockerfile
    ports:
      - "5000:80"
    networks:
      - beebilling-network

volumes:
  sql_data:

networks:
  beebilling-network:
